CREATE TABLE cliente (
  id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(200) NOT NULL,
  cpf VARCHAR(11) NOT NULL UNIQUE,
  rg VARCHAR(50) NOT NULL,
  email VARCHAR(254) NOT NULL,
  telefone VARCHAR(20) NOT NULL,
  cep VARCHAR(9) NOT NULL
);