package br.anhembi.topicosespeciais.atividade3.ui;

import br.anhembi.topicosespeciais.atividade3.dataAccess.ClienteRepository;
import br.anhembi.topicosespeciais.atividade3.dataAccess.DatabaseConnection;
import br.anhembi.topicosespeciais.atividade3.model.Cliente;
import java.awt.Component;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

public class ClienteForm extends javax.swing.JFrame {

    private ClienteRepository _repository;
    private Cliente _atual;
    
    public ClienteForm() {
        initComponents();
        
        DatabaseConnection connection;
        try {
            connection = new DatabaseConnection();
            this._repository = new ClienteRepository(connection);
        } catch (SQLException ex) {
            Logger.getLogger(ClienteForm.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this,"Não foi possível inicializar a conexão com o banco de dados.\r\n" + ex.toString(), "Alerta", JOptionPane.ERROR_MESSAGE);  
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        manipulacaoDadosPanel = new javax.swing.JPanel();
        adcionarButton = new javax.swing.JButton();
        excluirButton = new javax.swing.JButton();
        editarButton = new javax.swing.JButton();
        limparButton = new javax.swing.JButton();
        pesquisarButton = new javax.swing.JButton();
        formularioPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nomeText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cpfText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        rgText = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        emailText = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        telefoneText = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cepText = new javax.swing.JTextField();
        navegacaoDadosPanel = new javax.swing.JPanel();
        primeiroButton = new javax.swing.JButton();
        anteriorButton = new javax.swing.JButton();
        proximoButton = new javax.swing.JButton();
        ultimoButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cliente");

        adcionarButton.setText("Adicionar");
        adcionarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adcionarButtonMouseClicked(evt);
            }
        });
        manipulacaoDadosPanel.add(adcionarButton);

        excluirButton.setText("Excluir");
        excluirButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                excluirButtonMouseClicked(evt);
            }
        });
        manipulacaoDadosPanel.add(excluirButton);

        editarButton.setText("Editar");
        editarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editarButtonMouseClicked(evt);
            }
        });
        manipulacaoDadosPanel.add(editarButton);

        limparButton.setText("Limpar");
        limparButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                limparButtonMouseClicked(evt);
            }
        });
        manipulacaoDadosPanel.add(limparButton);

        pesquisarButton.setText("Pesquisar");
        pesquisarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pesquisarButtonMouseClicked(evt);
            }
        });
        manipulacaoDadosPanel.add(pesquisarButton);

        formularioPanel.setLayout(new java.awt.GridBagLayout());

        jLabel1.setLabelFor(nomeText);
        jLabel1.setText("Nome:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 4;
        gridBagConstraints.ipady = 18;
        formularioPanel.add(jLabel1, gridBagConstraints);

        nomeText.setPreferredSize(new java.awt.Dimension(300, 19));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 2;
        formularioPanel.add(nomeText, gridBagConstraints);

        jLabel2.setLabelFor(cpfText);
        jLabel2.setText("CPF:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 4;
        gridBagConstraints.ipady = 18;
        formularioPanel.add(jLabel2, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 2;
        formularioPanel.add(cpfText, gridBagConstraints);

        jLabel3.setLabelFor(rgText);
        jLabel3.setText("RG:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 4;
        gridBagConstraints.ipady = 18;
        formularioPanel.add(jLabel3, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 2;
        formularioPanel.add(rgText, gridBagConstraints);

        jLabel4.setLabelFor(emailText);
        jLabel4.setText("Email:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 4;
        gridBagConstraints.ipady = 18;
        formularioPanel.add(jLabel4, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 2;
        formularioPanel.add(emailText, gridBagConstraints);

        jLabel5.setLabelFor(telefoneText);
        jLabel5.setText("Telefone:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 4;
        gridBagConstraints.ipady = 18;
        formularioPanel.add(jLabel5, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 2;
        formularioPanel.add(telefoneText, gridBagConstraints);

        jLabel6.setLabelFor(cepText);
        jLabel6.setText("CEP:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 4;
        gridBagConstraints.ipady = 18;
        formularioPanel.add(jLabel6, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 2;
        formularioPanel.add(cepText, gridBagConstraints);

        primeiroButton.setText("Primeiro");
        primeiroButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                primeiroButtonMouseClicked(evt);
            }
        });
        navegacaoDadosPanel.add(primeiroButton);

        anteriorButton.setText("Anterior");
        anteriorButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                anteriorButtonMouseClicked(evt);
            }
        });
        navegacaoDadosPanel.add(anteriorButton);

        proximoButton.setText("Próximo");
        proximoButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                proximoButtonMouseClicked(evt);
            }
        });
        navegacaoDadosPanel.add(proximoButton);

        ultimoButton.setText("Último");
        ultimoButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ultimoButtonMouseClicked(evt);
            }
        });
        navegacaoDadosPanel.add(ultimoButton);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(manipulacaoDadosPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addComponent(formularioPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(navegacaoDadosPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(manipulacaoDadosPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(formularioPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(navegacaoDadosPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void excluirButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_excluirButtonMouseClicked
        if(this._atual == null)
            return;
        try {
            this._repository.Excluir(this._atual.getId());
            JOptionPane.showMessageDialog(null,"Registro excluido com sucesso!", "Alerta", JOptionPane.INFORMATION_MESSAGE);
            this.limparButtonMouseClicked(evt);
        } catch (SQLException ex) {
            mostrarErroSql(ex);
        }
    }//GEN-LAST:event_excluirButtonMouseClicked

    private void editarButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editarButtonMouseClicked
        formularioParaModel();
        try {
            this._repository.Atualizar(this._atual);
            JOptionPane.showMessageDialog(null,"Registro atualizado com sucesso!", "Alerta", JOptionPane.INFORMATION_MESSAGE);
        } catch (SQLException ex) {
            mostrarErroSql(ex);
        }
    }//GEN-LAST:event_editarButtonMouseClicked

    private void adcionarButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adcionarButtonMouseClicked
        formularioParaModel();
        try {
            this._repository.Inserir(this._atual);
            JOptionPane.showMessageDialog(null,"Registro inserido com sucesso!", "Alerta", JOptionPane.INFORMATION_MESSAGE);
        } catch (SQLException ex) {
            mostrarErroSql(ex);
        }
    }//GEN-LAST:event_adcionarButtonMouseClicked

    private void limparButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_limparButtonMouseClicked
        this._atual = null;
        for (Component c : formularioPanel.getComponents()) {
            if(c instanceof JTextField) {
                ((JTextField)c).setText("");
            }
        }
        
    }//GEN-LAST:event_limparButtonMouseClicked

    private void primeiroButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_primeiroButtonMouseClicked
        try {
            Cliente cliente = this._repository.Primeiro();
            if(cliente!=null) {
                this._atual = cliente;
                modelParaFormulario();
            }
            else {
                JOptionPane.showMessageDialog(null,"Não existe primeiro registro", "Alerta", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (SQLException ex) {
            mostrarErroSql(ex);
        }
    }//GEN-LAST:event_primeiroButtonMouseClicked

    private void ultimoButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ultimoButtonMouseClicked
        try {
            Cliente cliente = this._repository.Ultimo();
            if(cliente!=null) {
                this._atual = cliente;
                modelParaFormulario();
            }
            else {
                JOptionPane.showMessageDialog(null,"Não existe último registro", "Alerta", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (SQLException ex) {
            mostrarErroSql(ex);
        }
    }//GEN-LAST:event_ultimoButtonMouseClicked

    private void anteriorButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_anteriorButtonMouseClicked
        if(this._atual == null) {
            this.primeiroButtonMouseClicked(evt);
            return;
        }
        
        try {
            Cliente cliente = this._repository.Anterior(this._atual);
            if(cliente!=null) {
                this._atual = cliente;
                modelParaFormulario();
            }
            else {
                JOptionPane.showMessageDialog(null,"Não existe registro anterior", "Alerta", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (SQLException ex) {
            mostrarErroSql(ex);
        }
    }//GEN-LAST:event_anteriorButtonMouseClicked

    private void proximoButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_proximoButtonMouseClicked
        if(this._atual == null) {
            this.primeiroButtonMouseClicked(evt);
            return;
        }
        
        try {
            Cliente cliente = this._repository.Proximo(this._atual);
            if(cliente!=null) {
                this._atual = cliente;
                modelParaFormulario();
            }
            else {
                JOptionPane.showMessageDialog(null,"Não existe próximo registro", "Alerta", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (SQLException ex) {
            mostrarErroSql(ex);
        }
    }//GEN-LAST:event_proximoButtonMouseClicked

    private void pesquisarButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pesquisarButtonMouseClicked
        String cpf = JOptionPane.showInputDialog("Digite o CPF para pesquisa:");
        try {
            Cliente cliente = this._repository.Pesquisar(cpf);
            if(cliente!=null) {
                this._atual = cliente;
                modelParaFormulario();
            }
            else {
                JOptionPane.showMessageDialog(null,"Não foi encontrado nenhum registro", "Alerta", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (SQLException ex) {
            mostrarErroSql(ex);
        }
    }//GEN-LAST:event_pesquisarButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClienteForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClienteForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClienteForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClienteForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClienteForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adcionarButton;
    private javax.swing.JButton anteriorButton;
    private javax.swing.JTextField cepText;
    private javax.swing.JTextField cpfText;
    private javax.swing.JButton editarButton;
    private javax.swing.JTextField emailText;
    private javax.swing.JButton excluirButton;
    private javax.swing.JPanel formularioPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton limparButton;
    private javax.swing.JPanel manipulacaoDadosPanel;
    private javax.swing.JPanel navegacaoDadosPanel;
    private javax.swing.JTextField nomeText;
    private javax.swing.JButton pesquisarButton;
    private javax.swing.JButton primeiroButton;
    private javax.swing.JButton proximoButton;
    private javax.swing.JTextField rgText;
    private javax.swing.JTextField telefoneText;
    private javax.swing.JButton ultimoButton;
    // End of variables declaration//GEN-END:variables

    private void mostrarErroSql(SQLException ex) {
        JOptionPane.showMessageDialog(null,"Não foi possível completar a operação:\r\n" + ex.toString(), "Alerta", JOptionPane.ERROR_MESSAGE);
    }

    private void formularioParaModel() {
        int id = this._atual == null ? 0 : this._atual.getId();
        this._atual = new Cliente(id,
        nomeText.getText(),
        cpfText.getText(),
        rgText.getText(),
        emailText.getText(),
        telefoneText.getText(),
        cepText.getText());
    }

    private void modelParaFormulario() {
        this.nomeText.setText(this._atual.getNome());
        this.cpfText.setText(this._atual.getCpf());
        this.rgText.setText(this._atual.getRg());
        this.emailText.setText(this._atual.getEmail());
        this.telefoneText.setText(this._atual.getTelefone());
        this.cepText.setText(this._atual.getCep());
    }
}
